services:
  rest-server-kafka:
    extends:
      file: compose.common.yml
      service: rest-server-common
    build:
      args:
        TAG: kafka
    environment:
      KAFKA_HOST: kafka:29092
      KAFKA_TOPIC: tasks
    depends_on:
      kafka:
        condition: service_healthy
  elasticsearch-indexer-kafka:
    extends:
      file: compose.common.yml
      service: elasticsearch-indexer-common
    build:
      dockerfile: ./dockerfiles/elasticsearch-indexer-kafka.Dockerfile
    environment:
      KAFKA_HOST: kafka:29092
      KAFKA_TOPIC: tasks
    depends_on:
      kafka:
        condition: service_healthy
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 2181 || exit 1"]
      interval: 20s
      timeout: 1s
      retries: 5
  kafka:
    image: confluentinc/cp-kafka:7.6.2
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_BROKER_ID: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    healthcheck:
      test: kafka-topics --bootstrap-server kafka:29092 --list
      interval: 30s
      timeout: 10s
      retries: 5
  kafka_setup:
    image: confluentinc/cp-kafka:7.6.2
    restart: no
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:29092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic tasks --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:29092 --list
      "
