services:
  rest-server-rabbitmq:
    extends:
      file: compose.common.yml
      service: rest-server-common
    build:
      args:
        TAG: rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy
  elasticsearch-indexer-rabbitmq:
    extends:
      file: compose.common.yml
      service: elasticsearch-indexer-common
    build:
      dockerfile: ./dockerfiles/elasticsearch-indexer-rabbitmq.Dockerfile
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_started
  rabbitmq:
    image: rabbitmq:3.11.10-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 30s
      timeout: 30s
      retries: 5
