version: '3'
services:

  rocketride-postgres:
    image: postgres:14.1
    container_name: rocketride-postgres
    env_file:
      - app.env
    networks:
      - rocket-rides
    ports:
      - "5432:5432"
  
  stripe-mock:
    image: stripemock/stripe-mock:latest
    container_name: rocketride-stripe
    networks:
      - rocket-rides
    ports:
      - "12111:12111"
      - "12112:12112"

networks:
  rocket-rides:
    name: rocket-rides